### PR TITLE
support heroku status via '/current-status' API endpoint

### LINKED ISSUE #26: Add Heroku Status command
There is currently a `heroku-status` hubot script at https://github.com/github/hubot-scripts/blob/master/src/scripts/heroku-status.coffee . However, if my understanding of how the hubot eco-system has changed is correct, additional pull requests into hubot-scripts is no longer the preferred method. I think pulling that same functionality into this script would make sense, especially for verifying if Heroku is functioning correctly. It would not need any of the API auth, as the status endpoint is public.

I would be more than willing to submit a PR for this, but I wanted to see if you felt this project could use that functionality before I forked and added the code!

### PR DESCRIPTION
**Pull request by jacobsmith**
This PR closes #26.

Often times, I find myself wanting to check heroku's status to detect whether a failure is on my end, or on theirs. This PR adds support for `hubot heroku status`, which will give the current status of Heroku, along with a list of any issues that Heroku deems important enough to include in their default `current-status` endpoint. (I would imagine it is time-sensitive to include certain issues that are less than X number of hours old).

This PR gives the status of both Production and Development heroku endpoints and, if either of them are not "green", will iterate over all of the issues that are included in the response, giving
- Title
- Resolution status (true or false)
- Created At
- Updated At
- A link to Heroku's overview page of this specific issue, if a user wants additional information

I've included additional tests and fixtures to mock the response of the Heroku `current-status` endpoint. 

Please let me know if there's anything you'd like me to add or change!

Thanks,
Jacob

### CODE REVIEW

**Comment by daemonsy** [comment]
Hey @jacobsmith this looks good. :+1: 

Can you post a message of how the status message is supposed to look like (especially if both the environments have issues). 

I'll then just check it out and merge the PR :)

**Comment by jacobsmith** [comment]
Yeah, I'd be happy to! I'm having a little bit of trouble being able to run this locally (I usually am working with single-script packages, so just copying the `command.coffee` file to `scripts/` works fine, or I'm just calling out to it in the `external-scripts.json` file). Mind giving me some pointers?

I've gone to my `hubot-heroku` repo and run `npm link`, then gone to my `hubot` repo and run `npm link hubot-heroku` -- I'm betting there's *some* way I need to tell `hubot` to load the `hubot-heroku` module, but I cannot seem to figure it out! Any direction would be much appreciated! (:

**Comment by daemonsy** [comment]
Any luck with the text output? Don't mean to rush, just because this is close to :shipit:ing. Don't want to be a blocker :) 

For context, reason why I asked for the text is so that we can compare the text output you envisioned with tests on the end platforms, I test on Slack and Flowdock, to see if they all look the same / look good.

**Comment by jacobsmith** [comment]
I actually hit a blocker where I'm getting a 404 when I try and call
`heroku.get('/current-status')`, so I'm betting the actual URL it is
creating is not completely correct? It might be that most of the
`heroku.get` methods are actually trying to use the private APIs that need
authentication, and this might be the only public URL. I'm going to try
using just regular `robot.http.get('https://HEROKU_API_STATUS')` and see if
that gets us any closer -- I'll keep you posted on the progress!

**Comment by jacobsmith** [comment]
I'm going to close this as it's 2 years old and I'm not even sure if I still have the code on my computer! Sorry for the clutter! If anyone finds this in the future, feel free to use this work as a starting point (:

**Pull request closed without merging**
